apiVersion: v1
kind: Pod
metadata:
  name: app-user
  labels:
    app: app-user		# label of the pod
spec:
  containers:
    - image: boussettahichem/myrepo:user0.1
      name: app-user
      ports:
        - containerPort: 7000

