apiVersion: v1
kind: Service
metadata:
  name: app-user-lb
spec:
  type: LoadBalancer
  ports:
  - name: http-user
    port: 7000
    protocol: TCP
    targetPort: 7000
  selector:
    app: app-user
---
apiVersion: v1
kind: Pod
metadata:
  name: app-user
  labels:
    app: app-user		# label of the pod
spec:
  containers:
    - image: boussettahichem/myrepo:user0.1
      name: app-user
      env:
        - name: SPRING_APPLICATION_JSON
          value: '{"server" : {"port" : 7000}}'
      ports:
        - containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: app-car-lb
spec:
  type: LoadBalancer
  ports:
  - name: http-car
    port: 7001
    protocol: TCP
    targetPort: 7001
  selector:
    app: app-car
---
apiVersion: v1
kind: Pod
metadata:
  name: app-car
  labels:
    app: app-car
spec:
  containers:
    - image: boussettahichem/myrepo:car0.1
      name: app-car
      env:
        - name: SPRING_APPLICATION_JSON
          value: '{"server" : {"port" : 7001}}'
      ports:
        - containerPort: 7001
---
apiVersion: v1
kind: Service
metadata:
  name: app-insurance-lb
spec:
  type: LoadBalancer
  ports:
  - name: http-insurance
    port: 7002
    protocol: TCP
    targetPort: 7002
  selector:
    app: app-insurance
---
apiVersion: v1
kind: Pod
metadata:
  name: app-insurance
  labels:
    app: app-insurance
spec:
  containers:
    - image: boussettahichem/myrepo:insurance0.1
      name: app-insurance
      env:
        - name: SPRING_APPLICATION_JSON
          value: '{"server" : {"port" : 7002}, "user" : {"users" : {"url" : "http://app-user-lb:7000/users"}}, "car" : {"cars" : {"url" : "http://app-car-lb:7001/cars"}}}'
      ports:
        - containerPort: 7002
