apiVersion: v1
kind: Pod
metadata:
  name: app-car
  labels:
    app: app-car
spec:
  containers:
    - image: boussettahichem/myrepo:car0.1
      name: app-car
      ports:
        - containerPort: 9090

