apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-insurance
spec:
  selector:
    matchLabels:
      app: app-insurance
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: app-insurance
    spec:
      containers:
        - image: boussettahichem/myrepo:insurance0.1
          imagePullPolicy: Never							# Set to Always to force pulling the image at each deployment
          name: app-insurance
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{"user" : {"users" : {"url" : "http://app-user-lb:7070/users"}}, "car" : {"cars" : {"url" : "http://app-car-lb:9090/cars"}}}'
          ports:
            - containerPort: 7002

