apiVersion: v1
kind: Pod
metadata:
  name: app-user
  labels:
    app: app-user		# label of the pod
spec:
  containers:
    - image: acvcontainerregistry.azurecr.io/user:2.4
      name: app-user
      ports:
        - containerPort: 7000

